export const fieldInfo = [
  { name: "Catalog", type: "string", explanation: "Catalogue (H=Hipparcos)" },
  { name: "HIP", type: "int", explanation: "Identifier (HIP number)" },
  { name: "Proxy", type: "string", explanation: "Proximity flag" },
  { name: "RAhms", type: "string", explanation: "Right ascension in h m s, ICRS (J1991.25)" },
  { name: "DEdms", type: "string", explanation: "Declination in deg ' \", ICRS (J1991.25)" },
  { name: "Vmag", type: "float", explanation: "Magnitude in Johnson V" },
  { name: "VarFlag", type: "int", explanation: "Coarse variability flag" },
  { name: "r_Vmag", type: "string", explanation: "Source of magnitude" },
  { name: "RAdeg", type: "float", explanation: "Alpha, degrees (ICRS, Epoch=J1991.25)" },
  { name: "DEdeg", type: "float", explanation: "Delta, degrees (ICRS, Epoch=J1991.25)" },
  { name: "AstroRef", type: "string", explanation: "Reference flag for astrometry" },
  { name: "Plx", type: "float", explanation: "Trigonometric parallax" },
  { name: "pmRA", type: "float", explanation: "Proper motion mu_alpha.cos(delta), ICRS" },
  { name: "pmDE", type: "float", explanation: "Proper motion mu_delta, ICRS" },
  { name: "e_RAdeg", type: "float", explanation: "Standard error in RA*cos(DEdeg)" },
  { name: "e_DEdeg", type: "float", explanation: "Standard error in DE" },
  { name: "e_Plx", type: "float", explanation: "Standard error in Plx" },
  { name: "e_pmRA", type: "float", explanation: "Standard error in pmRA" },
  { name: "e_pmDE", type: "float", explanation: "Standard error in pmDE" },
  { name: "DE_RA", type: "float", explanation: "Correlation, DE/RA*cos(delta)" },
  { name: "Plx_RA", type: "float", explanation: "Correlation, Plx/RA*cos(delta)" },
  { name: "Plx_DE", type: "float", explanation: "Correlation, Plx/DE" },
  { name: "pmRA_RA", type: "float", explanation: "Correlation, pmRA/RA*cos(delta)" },
  { name: "pmRA_DE", type: "float", explanation: "Correlation, pmRA/DE" },
  { name: "pmRA_Plx", type: "float", explanation: "Correlation, pmRA/Plx" },
  { name: "pmDE_RA", type: "float", explanation: "Correlation, pmDE/RA*cos(delta)" },
  { name: "pmDE_DE", type: "float", explanation: "Correlation, pmDE/DE" },
  { name: "pmDE_Plx", type: "float", explanation: "Correlation, pmDE/Plx" },
  { name: "pmDE_pmRA", type: "float", explanation: "Correlation, pmDE/pmRA" },
  { name: "F1", type: "int", explanation: "Percentage of rejected data" },
  { name: "F2", type: "float", explanation: "Goodness-of-fit parameter" },
  { name: "HIP_repetition", type: "int", explanation: "HIP number (repetition)" },
  { name: "BTmag", type: "float", explanation: "Mean BT magnitude" },
  { name: "e_BTmag", type: "float", explanation: "Standard error on BTmag" },
  { name: "VTmag", type: "float", explanation: "Mean VT magnitude" },
  { name: "e_VTmag", type: "float", explanation: "Standard error on VTmag" },
  { name: "m_BTmag", type: "string", explanation: "Reference flag for BT and VTmag" },
  { name: "B_V", type: "float", explanation: "Johnson B-V colour" },
  { name: "e_B_V", type: "float", explanation: "Standard error on B-V" },
  { name: "r_B_V", type: "string", explanation: "Source of B-V from Ground or Tycho" },
  { name: "V_I", type: "float", explanation: "Colour index in Cousins' system" },
  { name: "e_V_I", type: "float", explanation: "Standard error on V-I" },
  { name: "r_V_I", type: "string", explanation: "Source of V-I" },
  { name: "CombMag", type: "string", explanation: "Flag for combined Vmag, B-V, V-I" },
  { name: "Hpmag", type: "float", explanation: "Median magnitude in Hipparcos system" },
  { name: "e_Hpmag", type: "float", explanation: "Standard error on Hpmag" },
  { name: "Hpscat", type: "float", explanation: "Scatter on Hpmag" },
  { name: "o_Hpmag", type: "int", explanation: "Number of observations for Hpmag" },
  { name: "m_Hpmag", type: "string", explanation: "Reference flag for Hpmag" },
  { name: "Hpmax", type: "float", explanation: "Hpmag at maximum (5th percentile)" },
  { name: "HPmin", type: "float", explanation: "Hpmag at minimum (95th percentile)" },
  { name: "Period", type: "float", explanation: "Variability period (days)" },
  { name: "HvarType", type: "string", explanation: "Variability type" },
  { name: "moreVar", type: "string", explanation: "Additional data about variability" },
  { name: "morePhoto", type: "string", explanation: "Light curve Annex" },
  { name: "CCDM", type: "string", explanation: "CCDM identifier" },
  { name: "n_CCDM", type: "string", explanation: "Historical status flag" },
  { name: "Nsys", type: "int", explanation: "Number of entries with same CCDM" },
  { name: "Ncomp", type: "int", explanation: "Number of components in this entry" },
  { name: "MultFlag", type: "string", explanation: "Double/Multiple Systems flag" },
  { name: "Source", type: "string", explanation: "Astrometric source flag" },
  { name: "Qual", type: "string", explanation: "Solution quality" },
  { name: "m_HIP", type: "string", explanation: "Component identifiers" },
  { name: "theta", type: "int", explanation: "Position angle between components" },
  { name: "rho", type: "float", explanation: "Angular separation between components" },
  { name: "e_rho", type: "float", explanation: "Standard error on rho" },
  { name: "dHp", type: "float", explanation: "Magnitude difference of components" },
  { name: "e_dHp", type: "float", explanation: "Standard error on dHp" },
  { name: "Survey", type: "string", explanation: "Flag indicating a Survey Star" },
  { name: "Chart", type: "string", explanation: "Identification Chart" },
  { name: "Notes", type: "string", explanation: "Existence of notes" },
  { name: "HD", type: "int", explanation: "HD number" },
  { name: "BD", type: "string", explanation: "Bonner DM" },
  { name: "CoD", type: "string", explanation: "Cordoba Durchmusterung (DM)" },
  { name: "CPD", type: "string", explanation: "Cape Photographic DM" },
  { name: "V_Ired", type: "float", explanation: "V-I used for reductions" },
  { name: "SpType", type: "string", explanation: "Spectral type" },
  { name: "r_SpType", type: "string", explanation: "Source of spectral type" }
];
